version: "3.3"
services: 
    server:
        image: itzg/minecraft-server:latest
        environment: 
            EULA: "TRUE"
            VERSION: "1.12.2"
            ONLINE_MODE: "FALSE"
            MEMORY: "2G"
        ports: 
            - "25565:25565"
        volumes: 
            - ./world:/data/world:rw
volumes: 
    world:
